language: python 

matrix:
  include:
    - os: linux
      python: "3.6"

    - os: osx 
      python: "3.6"
      osx_image: xcode10.2
      language: generic

before_install:
  - python3 -m pip install --upgrade pip

install:
  - python3 -m pip install -r requirements.txt

script:
  - pytest
