language: python 
os: linux

python:
  - "3.6"
  - "3.7"

before_install:
  - pip install --upgrade pip

install: 
  - pip install codecov
  - pip install -r requirements.txt
  - pip install .
 
script:
  - pytest
  
after_success:
  - codecov
